language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install --dev --config.interactive=0
  - grunt --version
  - bower --version

script:
  - grunt jshint test